# This is a basic workflow to help you get started with Actions

name: Deploy Docker App

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy".
  deploy:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Configuration of the job; these variables are also present in DockerEnvList
    # Secrets are configured on the github repo
    env:
      TEST_VAR: "test variable"
      SECRET: ${{ secrets.SECRET_MESSAGE }}
      APP_NAME: "davidtest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2     

      - name: List all current containers and images
        run: |
          echo "List of all docker containers:"
          docker container ls -a 
          echo "List of all docker images:"
          docker images -a 

      - name: Remove old docker containers and images
        run: |
          echo "Containers that are removed:"
          docker ps -q -a --filter "status=running" --filter "name=$env:APP_NAME" | ForEach-Object { docker kill $_ }
          docker ps -q -a --filter "status=exited" --filter "name=$env:APP_NAME" | ForEach-Object { docker rm $_ }
          echo "Images that are going to be removed:"
          docker images -a --filter "reference=${env:APP_NAME}:*"
          docker images -q -a --filter "reference=${env:APP_NAME}:*" | ForEach-Object { docker rmi $_ }

      - name: Build docker image
        run: | 
          docker build -t ${env:APP_NAME}:${{github.sha}} .   
          docker container run --env-file DockerEnvList --name $env:APP_NAME "${env:APP_NAME}:${{github.sha}}" python app.py

      - name: Check connection
        run: |
          echo "Check if website is reachable:"
          $response = curl https://www.google.com
          echo $response.statusCode
          echo "Check content markdown file:"
          Get-Content README.md

      - name: List all current containers and images
        run: |
          echo "List of all docker containers:"
          docker container ls -a 
          echo "List of all docker images:"
          docker images -a 
