# Eerste actie: kijk naar lijst van alle path available dictories + files
# Configuratie van jobs // github actions environment variables (niet allemaal encrypted)
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Configuration of the workflow
    env:
      TEST_VAR: "test variable"
      SECRET: ${{ secrets.SECRET_MESSAGE }}
      TEST_NAME: "davidtest"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: test global env
        run: |
          echo ${{env.TEST_NAME}}

      - name: List all current containers and images
        run: |
          echo "List of all docker containers:"
          docker container ls -a 
          echo "List of all docker images:"
          docker images -a 

      - name: Build docker image
        run: docker build -t $TEST_NAME:${{github.sha}} .

      #TODO: only kill containers if building was OK
      #TODO: use before filter of current github commit hash to filter images and containers
      - name: Kill and remove old docker containers and images
        run: |
          echo "$TEST_NAME:${{github.sha}}"
          $imageID = docker ps -q -a --reference "$TEST_NAME:${{github.sha}}"
          docker ps -a --filter "status=running" --format '{{.ID}} {{.Image}}' | findstr "davidtest" | ForEach-Object { docker kill $_.split(" ")[0] }
          docker ps -a --filter "status=exited" --format '{{.ID}} {{.Image}}' | findstr "davidtest" | ForEach-Object { docker rm $_.split(" ")[0] }
          docker images -q -a --filter "before=$imageID" | ForEach-Object { docker rmi $_ } 
 
      - name: Run docker container
        run: docker container run --env-file .env $TEST_NAME:${{github.sha}} python app.py

      - name: check connection
        run: |
          echo "Check if website is reachable"
          $response = curl https://www.google.com
          echo $response.statusCode
          echo "Check content markdown file"
          Get-Content README.md

      - name: List all current containers and images
        run: |
          echo "List of all docker containers:"
          docker container ls -a 
          echo "List of all docker images:"
          docker images -a 
