# Eerste actie: kijk naar lijst van alle path available dictories + files
# Configuratie van jobs // github actions environment variables (niet allemaal encrypted)
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: dotenv
        name: Dotenv Action
        uses: falti/dotenv-action@v0.2.5
        with:
          path: .env.dev
          log-variables: true

      # Runs a single docker command
      - name: Run a docker command
        run: docker container ls -a 

      - name: Build docker container
        run: docker build . test:latest
      
      - name: Run docker container
        run: docker run . test:latest

      # Runs a set of commands using the runners shell
      - name: Run a one-line script with a secret
        run: echo ${{ secrets.SECRET_MESSAGE }}

      # Runs a set of commands using the runners shell
      - name: Run a one-line script with an environment variable
        run: echo ${{ steps.dotenv.outputs.TEST_VAR }}

